include: package:flutter_lints/flutter.yaml

linter:
  rules:
    - always_use_package_imports
    - avoid_relative_lib_imports
    - require_trailing_commas
    - always_declare_return_types
    - prefer_final_locals
    - omit_local_variable_types
    - no_leading_underscores_for_local_identifiers
analyzer:
  plugins:
    - custom_lint
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
    - "lib/generated_plugin_registrant.dart"
    - "test/**"
  errors:
    unrelated_type_equality_checks: error
    invalid_annotation_target: ignore
    must_be_immutable: ignore

da ignorert_code_metrics:
  anti-patterns:
    - long-method
    - long-parameter-list
  metrics:
    cyclomatic-complexity: 20
    maximum-nesting-level: 5
    number-of-parameters: 4
    source-lines-of-code: 50
  metrics-exclude:
    - test/**
  rules:
    - newline-before-return
    - no-boolean-literal-compare
    - no-empty-block
    - prefer-trailing-comma
    - prefer-conditional-expressions
    - no-equal-then-else
