arb-dir: lib/localization
template-arb-file: app_en.arb
output-localization-file: app_localizations.dart
nullable-getter: false
untranslated-messages-file: untranslatedMessages.txt
synthetic-package: false
format: true
