import 'package:dropdown_button2/dropdown_button2.dart';
import 'package:flutter/material.dart';
import 'package:flutter_bloc/flutter_bloc.dart';
import 'package:flutter_screenutil/flutter_screenutil.dart';
import 'package:unipool/app/shared/button/dropdown_button.dart';
import 'package:unipool/core/constants/app_colors.dart';
import 'package:unipool/app/extensions/build_context_extension.dart';
import 'package:unipool/app/extensions/l10.dart';
import 'package:unipool/features/profile/create_profile/cubit/school_cubit.dart';

final class SchoolPickerDropdown extends StatelessWidget {
  const SchoolPickerDropdown({super.key});
  static const list = [
    "Adana Bilim ve Teknoloji Üniversitesi",
    "Çukurova Üniversitesi",
    "Adıyaman Üniversitesi",
    "Afyon Kocatepe Üniversitesi",
    "Afyonkarahisar Sağlık Bilimleri Üniversitesi",
    "Ağrı İbrahim Çeçen Üniversitesi",
    "Amasya Üniversitesi",
    "Anka Teknoloji Üniversitesi",
    "Ankara Hacı Bayram Veli Üniversitesi",
    "Ankara Medipol Üniversitesi",
    "Ankara Müzik ve Güzel Sanatlar Üniversitesi",
    "Ankara Sosyal Bilimler Üniversitesi",
    "Ankara Üniversitesi",
    "Ankara Yıldırım Beyazıt Üniversitesi",
    "Atılım Üniversitesi",
    "Başkent Üniversitesi",
    "Çankaya Üniversitesi",
    "Gazi Üniversitesi",
    "Hacettepe Üniversitesi",
    "İhsan Doğramacı Bilkent Üniversitesi",
    "Lokman Hekim Üniversitesi",
    "Orta Doğu Teknik Üniversitesi",
    "Ostim Teknik Üniversitesi",
    "Ted Üniversitesi",
    "Tobb Ekonomi ve Teknoloji Üniversitesi",
    "Türk Hava Kurumu Üniversitesi",
    "Ufuk Üniversitesi",
    "Yüksek İhtisas Üniversitesi",
    "Akdeniz Üniversitesi",
    "Alanya Alaaddin Keykubat Üniversitesi",
    "Alanya Hamdullah Emin Paşa Üniversitesi",
    "Antalya Akev Üniversitesi",
    "Antalya Bilim Üniversitesi",
    "Artvin Çoruh Üniversitesi",
    "Aydın Adnan Menderes Üniversitesi",
    "Balıkesir Üniversitesi",
    "Bandırma Onyedi Eylül Üniversitesi",
    "Bilecik Şeyh Edebali Üniversitesi",
    "Bingöl Üniversitesi",
    "Bitlis Eren Üniversitesi",
    "Bolu Abant İzzet Baysal Üniversitesi",
    "Burdur Mehmet Akif Ersoy Üniversitesi",
    "Bursa Teknik Üniversitesi",
    "Bursa Uludağ Üniversitesi",
    "Faruk Saraç Tasarım Meslek Yüksekokulu",
    "Çanakkale Onsekiz Mart Üniversitesi",
    "Çankırı Karatekin Üniversitesi",
    "Hitit Üniversitesi",
    "Pamukkale Üniversitesi",
    "Dicle Üniversitesi",
    "Trakya Üniversitesi",
    "Fırat Üniversitesi",
    "Erzincan Binali Yıldırım Üniversitesi",
    "Atatürk Üniversitesi",
    "Erzurum Teknik Üniversitesi",
    "Anadolu Üniversitesi",
    "Eskişehir Osmangazi Üniversitesi",
    "Eskişehir Teknik Üniversitesi",
    "Gaziantep Bilim ve Teknoloji Üniversitesi",
    "Gaziantep Üniversitesi",
    "Hasan Kalyoncu Üniversitesi",
    "Sanko Üniversitesi",
    "Giresun Üniversitesi",
    "Gümüşhane Üniversitesi",
    "Hakkari Üniversitesi",
    "Hatay Mustafa Kemal Üniversitesi",
    "İskenderun Teknik Üniversitesi",
    "Isparta Uygulamalı Bilimler Üniversitesi",
    "Süleyman Demirel Üniversitesi",
    "Çağ Üniversitesi",
    "Mersin Üniversitesi",
    "Tarsus Üniversitesi",
    "Toros Üniversitesi",
    "Acıbadem Mehmet Ali Aydınlar Üniversitesi",
    "Altınbaş Üniversitesi",
    "Ataşehir Adıgüzel Meslek Yüksekokulu",
    "Avrupa Meslek Yüksekokulu",
    "Bahçeşehir Üniversitesi",
    "Beykent Üniversitesi",
    "Beykoz Üniversitesi",
    "Bezm-i Âlem Vakıf Üniversitesi",
    "Biruni Üniversitesi",
    "Boğaziçi Üniversitesi",
    "Doğuş Üniversitesi",
    "Fatih Sultan Mehmet Vakıf Üniversitesi",
    "Fenerbahçe Üniversitesi",
    "Galatasaray Üniversitesi",
    "Haliç Üniversitesi",
    "Işık Üniversitesi",
    "İbn Haldun Üniversitesi",
    "İstanbul Arel Üniversitesi",
    "İstanbul Atlas Üniversitesi",
    "İstanbul Aydın Üniversitesi",
    "İstanbul Ayvansaray Üniversitesi",
    "İstanbul Bilgi Üniversitesi",
    "İstanbul Bilim Üniversitesi",
    "İstanbul Esenyurt Üniversitesi",
    "İstanbul Gedik Üniversitesi",
    "İstanbul Gelişim Üniversitesi",
    "İstanbul Kent Üniversitesi",
    "İstanbul Kültür Üniversitesi",
    "İstanbul Medeniyet Üniversitesi",
    "İstanbul Medipol Üniversitesi",
    "İstanbul Okan Üniversitesi",
    "İstanbul Rumeli Üniversitesi",
    "İstanbul Sabahattin Zaim Üniversitesi",
    "İstanbul Şehir Üniversitesi",
    "İstanbul Şişli Meslek Yüksekokulu",
    "İstanbul Teknik Üniversitesi",
    "İstanbul Ticaret Üniversitesi",
    "İstanbul Üniversitesi",
    "İstanbul Üniversitesi - Cerrahpaşa",
    "İstanbul Yeni Yüzyıl Üniversitesi",
    "İstanbul 29 Mayıs Üniversitesi",
    "İstinye Üniversitesi",
    "İzmir Kavram Meslek Yüksekokulu",
    "Kadir Has Üniversitesi",
    "Koç Üniversitesi",
    "Maltepe Üniversitesi",
    "Marmara Üniversitesi",
    "Mef Üniversitesi",
    "Mimar Sinan Güzel Sanatlar Üniversitesi",
    "Nişantaşı Üniversitesi",
    "Özyeğin Üniversitesi",
    "Piri Reis Üniversitesi",
    "Sabancı Üniversitesi",
    "Sağlık Bilimleri Üniversitesi",
    "Semerkand Bilim ve Medeniyet Üniversitesi",
    "Türk-Alman Üniversitesi",
    "Türkiye Uluslararası İslam, Bilim ve Teknoloji Üniversitesi",
    "Türk-Japon Bilim ve Teknoloji Üniversitesi",
    "Üsküdar Üniversitesi",
    "Yeditepe Üniversitesi",
    "Yıldız Teknik Üniversitesi",
    "Dokuz Eylül Üniversitesi",
    "Ege Üniversitesi",
    "İzmir Bakırçay Üniversitesi",
    "İzmir Demokrasi Üniversitesi",
    "İzmir Ekonomi Üniversitesi",
    "İzmir Katip Çelebi Üniversitesi",
    "İzmir Tınaztepe Üniversitesi",
    "İzmir Yüksek Teknoloji Enstitüsü",
    "Yaşar Üniversitesi",
    "Kafkas Üniversitesi",
    "Kastamonu Üniversitesi",
    "Abdullah Gül Üniversitesi",
    "Erciyes Üniversitesi",
    "Kayseri Üniversitesi",
    "Nuh Naci Yazgan Üniversitesi",
    "Kırklareli Üniversitesi",
    "Kırşehir Ahi Evran Üniversitesi",
    "Gebze Teknik Üniversitesi",
    "Kocaeli Üniversitesi",
    "Konya Gıda ve Tarım Üniversitesi",
    "Konya Teknik Üniversitesi",
    "Kto Karatay Üniversitesi",
    "Necmettin Erbakan Üniversitesi",
    "Selçuk Üniversitesi",
    "Kütahya Dumlupınar Üniversitesi",
    "Kütahya Sağlık Bilimleri Üniversitesi",
    "İnönü Üniversitesi",
    "Malatya Turgut Özal Üniversitesi",
    "Manisa Celâl Bayar Üniversitesi",
    "Kahramanmaraş İstiklal Üniversitesi",
    "Kahramanmaraş Sütçü İmam Üniversitesi",
    "Mardin Artuklu Üniversitesi",
    "Muğla Sıtkı Koçman Üniversitesi",
    "Muş Alparslan Üniversitesi",
    "Kapadokya Üniversitesi",
    "Nevşehir Hacı Bektaş Veli Üniversitesi",
    "Niğde Ömer Halisdemir Üniversitesi",
    "Ordu Üniversitesi",
    "Recep Tayyip Erdoğan Üniversitesi",
    "Samsun Üniversitesi",
    "Sakarya Uygulamalı Bilimler Üniversitesi",
    "Sakarya Üniversitesi",
    "Ondokuz Mayıs Üniversitesi",
    "Siirt Üniversitesi",
    "Sinop Üniversitesi",
    "Sivas Bilim ve Teknoloji Üniversitesi",
    "Sivas Cumhuriyet Üniversitesi",
    "Tekirdağ Namık Kemal Üniversitesi",
    "Tokat Gaziosmanpaşa Üniversitesi",
    "Avrasya Üniversitesi",
    "Karadeniz Teknik Üniversitesi",
    "Trabzon Üniversitesi",
    "Munzur Üniversitesi",
    "Harran Üniversitesi",
    "Uşak Üniversitesi",
    "Van Yüzüncü Yıl Üniversitesi",
    "Yozgat Bozok Üniversitesi",
    "Zonguldak Bülent Ecevit Üniversitesi",
    "Aksaray Üniversitesi",
    "Bayburt Üniversitesi",
    "Karamanoğlu Mehmetbey Üniversitesi",
    "Kırıkkale Üniversitesi",
    "Batman Üniversitesi",
    "Şırnak Üniversitesi",
    "Bartın Üniversitesi",
    "Ardahan Üniversitesi",
    "Iğdır Üniversitesi",
    "Yalova Üniversitesi",
    "Karabük Üniversitesi",
    "Kilis 7 Aralık Üniversitesi",
    "Osmaniye Korkut Ata Üniversitesi",
    "Düzce Üniversitesi",
  ];
  @override
  Widget build(BuildContext context) {
    final textEditingController = TextEditingController();
    return BlocBuilder<SchoolCubit, String?>(
      builder: (context, state) {
        return CustomDropdownButton(
          dropdownSearchData: DropdownSearchData(
            searchController: textEditingController,
            searchInnerWidgetHeight: 50,
            searchInnerWidget: Container(
              height: 50.h,
              padding: const EdgeInsets.only(
                top: 8,
                bottom: 4,
                right: 8,
                left: 8,
              ),
              child: TextFormField(
                expands: true,
                maxLines: null,
                controller: textEditingController,
                decoration: InputDecoration(
                  isDense: true,
                  contentPadding: EdgeInsets.symmetric(
                    horizontal: 10.w,
                    vertical: 8.h,
                  ),
                  hintText: context.l10n.searchForUniversity,
                  hintStyle: context.textTheme.bodyMedium,
                  border: OutlineInputBorder(
                    borderRadius: BorderRadius.circular(8),
                    borderSide: BorderSide(
                      color: AppColors.kGreyLight1,
                    ),
                  ),
                  focusedBorder: OutlineInputBorder(
                    borderRadius: BorderRadius.circular(8),
                    borderSide: BorderSide(
                      color: AppColors.kGreyLight1,
                    ),
                  ),
                ),
              ),
            ),
            searchMatchFn: (item, searchValue) {
              return item.value.toString().toLowerCase().contains(searchValue.toLowerCase());
            },
          ),
          hint: context.l10n.university,
          buttonWidth: double.infinity,
          buttonHeight: 64.h,
          bgColor: AppColors.kGreyLight1,
          dropdownDecoration: BoxDecoration(
            color: AppColors.kWhite,
            borderRadius: BorderRadius.circular(8.r),
          ),
          dropdownItems: list,
          onChanged: (value) {
            if (value != null) {
              context.read<SchoolCubit>().setSchool(value);
            }
          },
          value: state,
          selectedItemBuilder: (context) {
            return list.map(
              (item) {
                return Container(
                  alignment: AlignmentDirectional.centerStart,
                  child: Text(
                    item,
                    style: context.textTheme.bodyMedium,
                    maxLines: 1,
                  ),
                );
              },
            ).toList();
          },
        );
      },
    );
  }
}
